# NOTE: Have an issues with pnp on current machine, so I'm using classic mode
nodeLinker: node-modules

packageExtensions:
  babel-plugin-styled-components@2.1.4:
    peerDependencies:
      "@babel/core": ^7.0.0-0
  styled-components@5.3.9:
    peerDependencies:
      "@babel/core": ^7.0.0-0

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
    - win32
    - arm64

yarnPath: .yarn/releases/yarn-3.2.3.cjs
